=== freeVM/freeVM/enhanced/buildtest/tests/vts/vm/src/test/test.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!ELEMENT Test (Copyright+, Author+, (MulticaseTestDescription|APITestDescription|Description), Keyword*, Source+, Modification*, Runner, Resource*, Restriction*)>
<!ATTLIST Test
	ID CDATA #REQUIRED
	date-of-creation CDATA #REQUIRED
	timeout CDATA #REQUIRED>
<!ELEMENT Copyright EMPTY>
<!ATTLIST Copyright
	value CDATA #REQUIRED>
<!ELEMENT Author EMPTY>
<!ATTLIST Author
	value CDATA #REQUIRED>
<!ELEMENT MulticaseTestDescription (TestedClass, Case+)>
<!ELEMENT APITestDescription ((TestedClass, TestedMethod+)+, Description)>
<!ELEMENT TestedClass EMPTY>
<!ATTLIST TestedClass
	name CDATA #REQUIRED>
<!ELEMENT Case (TestedMethod+, (TestedClass, TestedMethod+)*, Precondition?, Description, Expected?)>
<!ATTLIST Case
	ID CDATA #REQUIRED>
<!ELEMENT TestedMethod EMPTY>
<!ATTLIST TestedMethod
	name CDATA #REQUIRED>
<!ELEMENT Precondition (#PCDATA)>
<!ELEMENT Expected (#PCDATA)>
<!ELEMENT Description ANY>
<!ELEMENT Keyword EMPTY>
<!ATTLIST Keyword
	name CDATA #REQUIRED>
<!ELEMENT Source EMPTY>
<!ATTLIST Source
	name CDATA #REQUIRED>
<!ELEMENT Modification EMPTY>
<!ATTLIST Modification
	date CDATA #REQUIRED
	author CDATA #REQUIRED>
<!ELEMENT Runner (Option*, Param+)>
<!ATTLIST Runner
	ID CDATA #REQUIRED>
<!ELEMENT Param (Option*)>
<!ATTLIST Param
	name CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT Option EMPTY>
<!ATTLIST Option
	name CDATA #IMPLIED
	value CDATA #IMPLIED>
<!ELEMENT Resource EMPTY>
<!ATTLIST Resource
	name CDATA #REQUIRED>
<!ELEMENT Restriction EMPTY>
<!ATTLIST Restriction
	name CDATA #REQUIRED>

=== freeVM/freeVM/enhanced/buildtest/tests/functional/src/test/functional/org/apache/harmony/test/func/api/java/security/cert/F_CertPathTest_04/F_CertPathTest_04.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='../../../../../../../../../../../test.xsl'?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM '../../../../../../../../../../../test.dtd'>
<Test
    ID="F_CertPathTest_04"
    date-of-creation="2005-10-04"
    timeout="1"
    >
    <!--
    -->
            
                
                <APITestDescription>
                    <TestedClass name="java.security.cert.CertificateFactory"/>
                    <TestedMethod name="public static final CertificateFactory getInstance(String type) throws CertificateException"/>
                    <TestedMethod name="public final Collection&lt;? extends Certificate&gt; generateCertificates(InputStream inStream) throws CertificateException"/>
                    <Testedmethod name="public final CertPath generateCertPath(List&lt;? extends Certificate&gt; certificates) throws CertificateException"/>
                    <TestedMethod name="public final Iterator&lt;String&gt; getCertPathEncodings()"/>
                    <TestedMethod name="public final CertPath generateCertPath(InputStream inStream, String encoding) throws CertificateException"/>

                    <TestedClass name="java.security.cert.X509CertSelector"/>
                    <TestedMethod name="public X509CertSelector()"/>
                    <TestedMethod name="public void setSubject(X500Principal subject)"/>
                    <TestedMethod name="public void setIssuer(X500Principal issuer)"/>

                    <TestedClass name="java.security.KeyStore"/>
                    <TestedMethod name="public static KeyStore getInstance(String type) throws KeyStoreException"/>
                    <TestedMethod name="public static final String getDefaultType()"/>
                    <TestedMethod name="public final void load(InputStream stream, char[] password) throws IOException, NoSuchAlgorithmException, CertificateException"/>

                    <TestedClass name="java.security.cert.PKIXParameters"/>
                    <TestedMethod name="public PKIXParameters(KeyStore keystore) throws KeyStoreException, InvalidAlgorithmParameterException"/>
                    <TestedMethod name="public void setDate(Date date)"/>
                    <TestedMethod name="public void setTargetCertConstraints(CertSelector selector)"/>
                    <TestedMethod name="public void setExplicitPolicyRequired(boolean val)"/>
                    <TestedMethod name="public void setRevocationEnabled(boolean val)"/>

                    <TestedClass name="java.security.cert.CertPathValidator"/>
                    <TestedMethod name="public static CertPathValidator getInstance(String algorithm) throws NoSuchAlgorithmException"/>
                    <TestedMethod name="public static final String getDefaultType()"/>
                    <TestedMethod name="public final CertPathValidatorResult validate(CertPath certPath, CertPathParameters params) throws CertPathValidatorException, InvalidAlgorithmParameterException"/>

                    <TestedClass name="java.security.cert.PKIXCertPathValidatorResult"/>
                    <TestedMethod name="public PublicKey getPublicKey()"/>
                    <TestedMethod name="public TrustAnchor getTrustAnchor()"/>

                    <TestedClass name="java.security.cert.TrustAnchor"/>
                    <TestedMethod name="public final X509Certificate getTrustedCert()"/>

                    <TestedClass name="java.security.cert.X509Certificate"/>
                    <TestedMethod name="public X500Principal getIssuerX500Principal()"/>
                    <TestedMethod name="public X500Principal getSubjectX500Principal()"/>
            
                    <Description>
                        Checks CertPath validation.
                    </Description>
                </APITestDescription>
                
                <Keyword name="functional"/>
                <Source name="F_CertPathTest_04.java"/>
                <Modification date="2005-10-04" />
            
                
        <Runner ID="Runtime">
                <Option name="-cp" value="$CP$PathSeparator$TestSuiteClassRoot$PathSeparator"/>
                   <Option name="-Dqe.class=$TestSuiteClassRoot"/>
                   <Option name="-Dqe.src=$TestSuiteTestRoot"/>
                <Param name="toRun" value="org.apache.harmony.test.func.api.java.security.cert.F_CertPathTest_04.F_CertPathTest_04">
                    <Option value="$TestDirectory$FileSeparatorauxiliary$FileSeparatorcert_test.cert"/>
                    <Option value="$TestDirectory$FileSeparatorauxiliary$FileSeparatorcert_test.store"/>
                </Param>
        </Runner>

        <Restriction name="OtherVMOnly"/>
</Test>

=== freeVM/freeVM/enhanced/buildtest/tests/functional/src/test/functional/org/apache/harmony/test/func/api/java/lang/F_FloatTest_01/F_FloatTest_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='../../../../../../../../../../test.xsl'?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM '../../../../../../../../../../test.dtd'>
<Test
    ID="F_FloatTest_01"
    date-of-creation="2004-11-24"
    timeout="1"
    >
    <!--
    -->
        
        
        <APITestDescription>
            <TestedClass name="java.lang.Float"/>
            <TestedMethod name="public Float(float value)"/>
            <TestedMethod name="public boolean equals(Object obj)"/>
            <TestedMethod name="public float floatValue()"/>
            <TestedMethod name="public static boolean isInfinite(float v)"/>
            <TestedMethod name="public static boolean isNaN(float v)"/>
            <TestedMethod name="public static String toString(float f)"/>
            <TestedMethod name="public static Float valueOf(String s)"/>
        
            <Description>
                Check correctness of types contvertations for Float.
            </Description>
        </APITestDescription>

        <Keyword name="functional"/>
        <Source name="F_FloatTest_01.java"/>
        <Modification date="2004-11-24" />

        <Runner ID="Runtime">
            <Param name="toRun" value="org.apache.harmony.test.func.api.java.lang.F_FloatTest_01.F_FloatTest_01"></Param>
        </Runner>
</Test>

=== freeVM/freeVM/enhanced/buildtest/tests/functional/src/test/functional/org/apache/harmony/test/func/api/java/security/cert/F_CertPathTest_05/F_CertPathTest_05.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='../../../../../../../../../../../test.xsl'?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM '../../../../../../../../../../../test.dtd'>
<Test
    ID="F_CertPathTest_05"
    date-of-creation="2005-10-05"
    timeout="1"
    >
    <!--
    -->
            
                
                <APITestDescription>
                    <TestedClass name="java.security.cert.CertificateFactory"/>
                    <TestedMethod name="public static final CertificateFactory getInstance(String type) throws CertificateException"/>
                    <TestedMethod name="public final Certificate generateCertificate(InputStream inStream) throws CertificateException"/>
                    <TestedMethod name="public final Collection&lt;? extends CRL&gt; generateCRLs(InputStream inStream) throws CRLException"/>
                    <TestedMethod name="public final CertPath generateCertPath(List&lt;? extends Certificate&gt; certificates) throws CertificateException"/>

                    <TestedClass name="java.security.cert.CollectionCertStoreParameters"/>
                    <TestedMethod name="public CollectionCertStoreParameters(Collection&lt;?&gt; collection)"/>


                    <TestedClass name="java.security.cert.CertStore"/>
                    <TestedMethod name="public static CertStore getInstance(String type, CertStoreParameters params) throws InvalidAlgorithmParameterException, NoSuchAlgorithmException"/>

                    <TestedClass name="java.security.cert.X509CertSelector"/>
                    <TestedMethod name="public X509CertSelector()"/>
                    <TestedMethod name="public void setSubject(byte[] subjectDN) throws IOException"/>
                    <TestedMethod name="public void setIssuer(byte[] issuerDN) throws IOException"/>

                    <TestedClass name="java.security.cert.TrustAnchor"/>
                    <TestedMethod name="public TrustAnchor(X500Principal caPrincipal, PublicKey pubKey, byte[] nameConstraints)"/>

                    <TestedClass name="java.security.cert.PKIXParameters"/>
                    <TestedMethod name="public PKIXParameters(Set&lt;TrustAnchor&gt; trustAnchors) throws InvalidAlgorithmParameterException"/>
                    <TestedMethod name="public void addCertStore(CertStore store)"/>
                    <TestedMethod name="public void setTargetCertConstraints(CertSelector selector)"/>

                    <TestedClass name="java.security.cert.CertPathValidator"/>
                    <TestedMethod name="public static CertPathValidator getInstance(String algorithm) throws NoSuchAlgorithmException"/>
                    <TestedMethod name="public static final String getDefaultType()"/>
                    <TestedMethod name="public final CertPathValidatorResult validate(CertPath certPath, CertPathParameters params) throws CertPathValidatorException, InvalidAlgorithmParameterException"/>
            
                    <Description>
                        Checks CertPath validation.
                    </Description>
                </APITestDescription>
                
                <Keyword name="functional"/>
                <Source name="F_CertPathTest_05.java"/>
                <Modification date="2005-10-05" />
            
                
        <Runner ID="Runtime">
                <Option name="-cp" value="$CP$PathSeparator$TestSuiteClassRoot$PathSeparator"/>
                   <Option name="-Dqe.class=$TestSuiteClassRoot"/>
                   <Option name="-Dqe.src=$TestSuiteTestRoot"/>
                <Param name="toRun" value="org.apache.harmony.test.func.api.java.security.cert.F_CertPathTest_05.F_CertPathTest_05">
                    <Option value="$TestDirectory$FileSeparatorauxiliary$FileSeparatorcert_test.cert"/>
                    <Option value="$TestDirectory$FileSeparatorauxiliary$FileSeparatorca_root.cert"/>
                    <Option value="$TestDirectory$FileSeparatorauxiliary$FileSeparatorcrl.pem"/>
                </Param>
        </Runner>

        <Restriction name="OtherVMOnly"/>
</Test>

=== freeVM/freeVM/enhanced/buildtest/tests/vts/vm/src/test/vm/jvms/instructions/loadStore/ldc_w/ldc_w05/ldc_w0504/ldc_w0504.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM "test.dtd">
<!--
Author: Ilia A. Leviev
Version: $Revision: 1.4 $
-->
<Test
  ID="ldc_w0504"
  date-of-creation="2005-04-29"
  timeout="1"
  >
  <Author value="Ilia A. Leviev"/>
  <Description>
    The test is against the ldc_w java virtual machine instruction. 
    It performs the following check.     
    The VerifyError is thrown if constant type of value at index  is CONSTANT_Utf8.
   Covered assertions assert_class633 assert_instr28a089
</Description>

  <Keyword name="verifier"/>

  

  <Source name="ldc_w0504n.ccodeh"/>

  <Runner ID="Runtime">
    <Param name="toRun" value="org.apache.harmony.vts.test.vm.jvms.share.vmVerifierRun">
      <Option name="load"/>
      <Option name="org.apache.harmony.vts.test.vm.jvms.instructions.loadStore.ldc_w.ldc_w05.ldc_w0504.ldc_w0504n"/>
      <Option name="java.lang.VerifyError"/>
    </Param>
  </Runner>
</Test>

=== freeVM/freeVM/enhanced/buildtest/tests/functional/src/test/functional/org/apache/harmony/test/func/api/java/io/FilterReader/FilterReaderTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='../../../../../../../../../../test.xsl'?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM '../../../../../../../../../../test.dtd'>
<!-- 
-->


<Test
    ID="FilterReaderTest"
    date-of-creation="2004-11-18"
    timeout="1"
    >

    
    
    
    <MulticaseTestDescription>
        <TestedClass name="java.io.FilterReader"/>

        <Case ID="testConstructor">
            <TestedMethod name="protected FilterReader(Reader in)"/>
            <Precondition></Precondition>
            <Description>create an instance of a child of FilterReader class with null argument - NPE id thrown. 
            Create an instance of a child of FilterReader class with StringReader as argument - 
            'in' field in this object == constructor argument</Description>
            <Expected></Expected>
        </Case>

        <Case ID="testClose">
            <TestedMethod name="close()"/>
            <Precondition>create the FilterReader object</Precondition>
            <Description>check that FilterReaderReader.close() can be called</Description>
            <Expected>no exception</Expected>
        </Case>

        <Case ID="testNullObjectInConstructor">
            <TestedMethod name="FilterReader(Reader)"/>
            <Precondition></Precondition>
            <Description>call constructor FilterReader(null)</Description>
            <Expected>NullPointerException</Expected>
        </Case>

        <Case ID="testReadChars0001">
            <TestedClass name="java.io.Reader"/>
            <TestedMethod name="public int read(char[] cbuf)"/>
            <Precondition>create a FilterReader object</Precondition>
            <Description>call FilterReader.read(char[])</Description>
            <Expected>proper values are read</Expected>
        </Case>

        <Case ID="testSkip">
            <TestedMethod name="public long skip(long n)"/>
            <Precondition>create a FilterReader object</Precondition>
            <Description>call FilterReader.skip(arg) and FilterReader.read() after it</Description>
            <Expected>proper value is read</Expected>
        </Case>

        <Case ID="testReady">
            <TestedMethod name="public boolean ready()"/>
            <Precondition>create a FilterReader object</Precondition>
            <Description>call FilterReader.ready()</Description>
            <Expected>return value is 'false'</Expected>
        </Case>

        <Case ID="testMarkSupported">
            <TestedMethod name="public boolean markSupported()"/>
            <Precondition>create a FilterReader object</Precondition>
            <Description>call FilterReader.markSupported()</Description>
            <Expected>return value is 'true'</Expected>
        </Case>

        <Case ID="testMark">
            <TestedMethod name="public void mark(int readAheadLimit)"/>
            <Precondition>create a FilterReader object</Precondition>
            <Description>call FilterReader.mark()</Description>
            <Expected>general contract for Reader is kept</Expected>
        </Case>

        <Case ID="testReset">
            <TestedMethod name="mark(int)"/>
            <TestedMethod name="reset()"/>
            <Precondition>create the FilterReader object</Precondition>
            <Description>read some amount of chars from it, then call mark(10), read next char from the stream,
            read 9 chars, call reset() and read char from the stream again
            </Description>
            <Expected>chars read just after mark() and just after reset() are equal</Expected>
        </Case>
    </MulticaseTestDescription>

    <Keyword name="functional"/>    
    
    <Source name="FilterReaderTest.java"/>

    <Runner ID="MultiCase">
        <Param name="toRun" value="org.apache.harmony.test.func.api.java.io.FilterReader.FilterReaderTest">
                <Option name="-reference" value="$ReferenceRuntime"/>
                <Option name="-tested" value="$TestedRuntime"/>
                <Option name="-temp" value="$TempStorage"/>
                <Option name="-usedCP" value="$CP"/>
                <Option name="-bootCP" value="$bootClassPath"/>
                <Option name="-atomic" value="$performance.tests.atomic"/>
                <Option name="-sets" value="$performance.tests.sets"/>
                <Option name="-mode" value="$performance.tests.mode"/>
                <Option name="-threads" value="$qa.threads"/>
        </Param>
    </Runner>
</Test>

=== freeVM/freeVM/enhanced/buildtest/tests/vts/vm/src/test/vm/jvms/classFile/attributes/sourceDebugExtension/sourceDebugExtension05/sourceDebugExtension05.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM "test.dtd">
<!--
Author:  Alexander V. Esin
Version: $Revision: 1.2 $
-->
<Test
  ID="sourceDebugExtension05"
  date-of-creation="2006-06-29"
  timeout="1"
  >
  <Author value="Alexander V. Esin"/>
  <Description>
    Checks that ClassFormatError is thrown on loading a class file which has 
    SourceDebugExtension attribute in class info structure which has attribute_length 
    item less than size of debug_extension[] array
    Negative testcase.
    Covered assertions assert_class548_04
  </Description>

  <Keyword name="JVMS3ed_specific"/>

  <Source name="sourceDebugExtension05n.ccode"/>

  <Runner ID="Runtime">
    <Param name="toRun" value="org.apache.harmony.vts.test.vm.jvms.share.vmVerifierRun">
          <Option name="load"/>
          <Option name="org.apache.harmony.vts.test.vm.jvms.classFile.attributes.sourceDebugExtension.sourceDebugExtension05.sourceDebugExtension05n"/>
          <Option name="java.lang.ClassFormatError"/>
    </Param>
  </Runner>
</Test>

=== freeVM/freeVM/enhanced/buildtest/tests/functional/src/test/functional/org/apache/harmony/test/func/reg/jit/btest5632/Btest5632.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='../../../../../../../../../test.xsl'?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->

<!--
-->

<!DOCTYPE Test SYSTEM '../../../../../../../../../test.dtd'>

<Test ID="Btest5632"
        date-of-creation="2005-11-14"
        timeout="10"
    >

    
    

    <Description>
        (vm crashes in some cases with enabled HLO 
        if a method has nested 'for (;;)' loop)
     
        Please, note that this is reproducible with HLO enabled only.
    </Description>

    <Keyword name="regression"/>
    <Keyword name="opt"/>
    <Keyword name="hlo"/>

    <Source name="Btest5632.java"/>

    <Runner ID="ExecuteRegression">
        <Param name="toRun" value="crash">
            <Option name="~opt"/>
            <Option name="~skipOff"/>
            <Option name="~testName=org.apache.harmony.test.func.reg.jit.btest5632.Btest5632"/>
        </Param>
    </Runner>

</Test>

=== freeVM/freeVM/enhanced/buildtest/tests/functional/src/test/functional/org/apache/harmony/test/func/reg/jit/btest9490/Btest9490.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='../../../../../../../../../test.xsl'?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->

<!--
-->

<!DOCTYPE Test SYSTEM '../../../../../../../../../test.dtd'>

<Test ID="Btest9490"
    date-of-creation="2006-08-24"
    timeout="1"    >
    
    
    

    <Description>
        (frem, drem produce incorrect results on JIT OPT if dividend
                   is (+/-)MAX_VALUE of corresponding type)
    </Description>

    <Keyword name="regression"/>
    <Keyword name="opt"/>

    <Source name="Btest9490.java"/>

    <Runner ID="ExecuteRegression">
        <Param name="toRun" value="crash">
            <Option name="~opt"/>
            <Option name="org.apache.harmony.test.func.reg.jit.btest9490.Btest9490"/>
        </Param>
    </Runner>

</Test>
