=== freeVM/freeVM/enhanced/buildtest/tests/vts/vm/src/test/test.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!ELEMENT Test (Copyright+, Author+, (MulticaseTestDescription|APITestDescription|Description), Keyword*, Source+, Modification*, Runner, Resource*, Restriction*)>
<!ATTLIST Test
	ID CDATA #REQUIRED
	date-of-creation CDATA #REQUIRED
	timeout CDATA #REQUIRED>
<!ELEMENT Copyright EMPTY>
<!ATTLIST Copyright
	value CDATA #REQUIRED>
<!ELEMENT Author EMPTY>
<!ATTLIST Author
	value CDATA #REQUIRED>
<!ELEMENT MulticaseTestDescription (TestedClass, Case+)>
<!ELEMENT APITestDescription ((TestedClass, TestedMethod+)+, Description)>
<!ELEMENT TestedClass EMPTY>
<!ATTLIST TestedClass
	name CDATA #REQUIRED>
<!ELEMENT Case (TestedMethod+, (TestedClass, TestedMethod+)*, Precondition?, Description, Expected?)>
<!ATTLIST Case
	ID CDATA #REQUIRED>
<!ELEMENT TestedMethod EMPTY>
<!ATTLIST TestedMethod
	name CDATA #REQUIRED>
<!ELEMENT Precondition (#PCDATA)>
<!ELEMENT Expected (#PCDATA)>
<!ELEMENT Description ANY>
<!ELEMENT Keyword EMPTY>
<!ATTLIST Keyword
	name CDATA #REQUIRED>
<!ELEMENT Source EMPTY>
<!ATTLIST Source
	name CDATA #REQUIRED>
<!ELEMENT Modification EMPTY>
<!ATTLIST Modification
	date CDATA #REQUIRED
	author CDATA #REQUIRED>
<!ELEMENT Runner (Option*, Param+)>
<!ATTLIST Runner
	ID CDATA #REQUIRED>
<!ELEMENT Param (Option*)>
<!ATTLIST Param
	name CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT Option EMPTY>
<!ATTLIST Option
	name CDATA #IMPLIED
	value CDATA #IMPLIED>
<!ELEMENT Resource EMPTY>
<!ATTLIST Resource
	name CDATA #REQUIRED>
<!ELEMENT Restriction EMPTY>
<!ATTLIST Restriction
	name CDATA #REQUIRED>

=== freeVM/freeVM/enhanced/buildtest/tests/vts/vm/src/test/vm/jvms/classLLI/loading/loading10/loading1001/loading1001userdef/loading1001userdef.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM "test.dtd">
<!--
Author:  Mikhail Bolotov
Version: $Revision: 1.1 $
-->
<Test
  ID="loading1001userdef"
  date-of-creation="2006-06-02"
  timeout="1"
  >
  <Author value="Mikhail Bolotov"/>
  <Description>
    Creates an array class using user-defined class loaders and 
    checks that the component type of the array class is equal to the class used at the creation of that array.
    Covered assertions assert_const101 assert_const104 assert_const105  
  </Description>

  <Source name="../../../share/ClassLoaderRunner.java"/>
  <Source name="loading1001userdefpA.java"/>
  <Source name="loading1001userdefpB.java"/>

  <Runner ID="Runtime">
    <Param name="toRun" value="org.apache.harmony.vts.test.vm.jvms.classLLI.loading.share.ClassLoaderRunner">
     <Option name="2"/>
     <Option name="org.apache.harmony.vts.test.vm.jvms.classLLI.loading.loading10.loading1001.loading1001userdef.loading1001userdefpA"/>
     <Option name="org.apache.harmony.vts.test.vm.jvms.classLLI.loading.loading10.loading1001.loading1001userdef.loading1001userdefpB"/>
    </Param>

  </Runner>

</Test>

=== freeVM/freeVM/tests/stress/qa/src/test/stress/org/apache/harmony/test/stress/classloader/MixThreads/WrongClasses/testCFE_RBytes2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements.  See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership.  The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied.  See the License for the
 specific language governing permissions and limitations
 under the License.
-->
<!DOCTYPE Test SYSTEM "test.dtd">
<!--
Author: Vera Y.Petrashkova
Version: $Revision: 1.5 $
-->
<Test
	ID="testCFE_RBytes2"
        date-of-creation="2005-11-14"
        timeout="1">
    	<Copyright value="apache"/>
        <Author value="Vera Y. Petrashkova"/>
        <Description>
            Start a lot of threads which
	         - try to load a lot of wrong classes;
        	This performance is repeated several times.
        	Parameters: 0 - used mode
        	            1 - number of iterations
        	            2 - number of threads
        	            3 - number of iterations for classes loading
        	            4 - number of used classesd
        	            5 - location of used classes 
        </Description>
        <Keyword name="stress"/>
        <Source name="testCFE_RBytes.java"/>        
        <Source name="../../share/WrongClasses/testCFE_RBytes_00.java"/>        
        <Source name="../../share/WrongClasses/testCFE_RBytes.java"/>                
        <Runner ID="Runtime">
            <Option value="-Dorg.apache.harmony.test.share.stress.ReliabilityRunner.params=
					org.apache.harmony.test.stress.classloader.MixThreads.WrongClasses.testCFE_RBytes {}"/>
            <Option value="-Dorg.apache.harmony.test.stress.classloader.MixThreads.WrongClasses.testCFE_RBytes.arg0=1"/>
            <Option value="-Dorg.apache.harmony.test.stress.classloader.MixThreads.WrongClasses.testCFE_RBytes.arg1=2"/>
            <Option value="-Dorg.apache.harmony.test.stress.classloader.MixThreads.WrongClasses.testCFE_RBytes.arg2=5"/>
            <Option value="-Dorg.apache.harmony.test.stress.classloader.MixThreads.WrongClasses.testCFE_RBytes.arg3=100"/>
            <Option value="-Dorg.apache.harmony.test.stress.classloader.MixThreads.WrongClasses.testCFE_RBytes.arg4=5"/>
            <Option value="-Dorg.apache.harmony.test.stress.classloader.MixThreads.WrongClasses.testCFE_RBytes.arg5=$TestSuiteRoot/bin/classes"/>
		<Param name="toRun" value="org.apache.harmony.test.share.stress.ReliabilityRunner">
		</Param>
		</Runner>
		<Restriction name="OtherVMOnly"/>
</Test>

=== freeVM/freeVM/tests/stress/qa/src/test/stress/org/apache/harmony/test/stress/gc/frag/FragmentationBadFinalizeTest2/FragmentationBadFinalizeTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements.  See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership.  The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied.  See the License for the
 specific language governing permissions and limitations
 under the License.
-->
<!DOCTYPE Test SYSTEM "test.dtd">
<Test
	ID="FragmentationBadFinalizeTest2"
        date-of-creation="2006-01-31"
        timeout="2"
        >
        <!--
        Author:  Alexander Esin
        Version: $Revision: 1.5 $
        -->
    	<Copyright value="apache"/>
        <Author value="Alexander Esin"/>
		<APITestDescription>
			<TestedClass name="java.lang.Object"/>
			<TestedMethod name="protected void finalize()"/>
        	<Description>
                   Creates many objects of different sizes (10 bytes : 32MB), delete some of them (every 2d, 3d etc, this step is varied in a loop). Each object has defined finalize() method, which uses reference to variable defined in the main program in which it is assigned to null. Make sure that total allocated objects size does not reach initial size of heap. Check if OutOfMemoryError not thrown. Check if finalize() methods are invoked.
        	</Description>
		</APITestDescription>
        
        <Keyword name="stress"/>
        <Source name="../share/FragmentationBadFinalizeTest2.java"/>
        <Modification date="2006-01-31" author="Alexander Esin"/>

        <Runner ID="Runtime">
                <Option name="-Xmx64m"/>
               	<Option value="-Dorg.apache.harmony.test.share.stress.ReliabilityRunner.params=
					org.apache.harmony.test.stress.gc.frag.share.FragmentationBadFinalizeTest2 {}"/>
				<Option value="-Dorg.apache.harmony.test.stress.gc.frag.share.FragmentationAbstractTest.MAX_MEM=40000000"/>
			<Param name="toRun" value="org.apache.harmony.test.share.stress.ReliabilityRunner">
			</Param>
		</Runner>
	<Restriction name="OtherVMOnly"/>
</Test>

=== freeVM/freeVM/enhanced/buildtest/tests/vts/vm/src/test/vm/jvms/classFile/attributes/enclosingMethod/enclosingMethod09/enclosingMethod09.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM "test.dtd">
<!--
Author:  Alexander V. Esin
Version: $Revision: 1.1 $
-->
<Test
  ID="enclosingMethod09"
  date-of-creation="2006-06-30"
  timeout="1"
  >
  <Author value="Alexander V. Esin"/>
  <Description>
    Checks that VM throws ClassFormatError on loading a class which has 
    EnclosingMethod attribute in which method_index refers outside constant_pool.
    Negative test.
    Covered assertions assert_class527_08
  </Description>

  <Keyword name="JVMS3ed_specific"/>

  <Source name="enclosingMethod09n.ccode"/>
  <Source name="enclosingMethod09n$1EnclosingMethod.ccode"/>
  <Runner ID="Runtime">
    <Param name="toRun" value="org.apache.harmony.vts.test.vm.jvms.share.vmVerifierRun">
                <Option name="load"/>
                <Option name="org.apache.harmony.vts.test.vm.jvms.classFile.attributes.enclosingMethod.enclosingMethod09.enclosingMethod09n$1EnclosingMethod"/>
                <Option name="java.lang.ClassFormatError"/>
    </Param>
  </Runner>
</Test>

=== freeVM/freeVM/enhanced/buildtest/tests/functional/src/test/functional/org/apache/harmony/test/func/api/java/lang/reflect/F_ReflectionTest_04/F_ReflectionTest_04.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='../../../../../../../../../../../test.xsl'?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM '../../../../../../../../../../../test.dtd'>
<Test
    ID="F_ReflectionTest_04"
    date-of-creation="2004-12-08"
    timeout="1"
    >
    <!--
    -->
        
        
        <APITestDescription>
            <TestedClass name="java.lang.ClassLoader"/>
            <TestedMethod name="protected ClassLoader()"/>
            <TestedMethod name="public Class&lt;?&gt; loadClass(String name) throws ClassNotFoundException"/>
            
            <TestedClass name="java.lang.Class"/>
            <TestedMethod name="public Constructor&lt;T&gt; getConstructor(Class... parameterTypes) throws NoSuchMethodException, SecurityException"/>
            <TestedMethod name="public boolean isInstance(Object obj)"/>
            
            <TestedClass name="java.lang.reflect.Array"/>
            <TestedMethod name="public static Object newInstance(Class&lt;?&gt; componentType, int length) throws NegativeArraySizeException"/>
            <TestedMethod name="public static int getLength(Object array)"/>
            <TestedMethod name="public static void set(Object array, int index, Object value)"/>
            <TestedMethod name="public static Object get(Object array, int index)"/>
            
            <TestedClass name="java.lang.reflect.Constructor"/>
            <TestedMethod name="public Class&lt;?&gt; getDeclaringClass()"/>
            <TestedMethod name="public T newInstance(Object... initargs) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException"/>
        
            <Description>
                Create array of objects of dynamically loading class for testing Array and Constructor.
            </Description>
        </APITestDescription>

        <Keyword name="functional"/>
        <Source name="F_ReflectionTest_04.java"/>
        <Modification date="2004-12-21" />

        <Runner ID="Runtime">
            <Param name="toRun" value="org.apache.harmony.test.func.api.java.lang.reflect.F_ReflectionTest_04.F_ReflectionTest_04"></Param>
        </Runner>
</Test>

=== freeVM/freeVM/enhanced/buildtest/tests/vts/vm/src/test/vm/jni/references/DeleteLocalRefTest/DeleteLocalRefTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM "test.dtd">
<!--
Author: Petr Ivanov
Version: $Revision: 1.3 $
-->

<Test
    ID="DeleteLocalRefTest"
    date-of-creation="11-02-2005"
    timeout="1"
    >   
        <Author value="Petr Ivanov"/>
        <Description>
            <TestedMethod name="DeleteLocalRef()"/>
            Test creates the local object in native and creates a weak ref
            to it, then deletes this local ref and invokes System.gc(); 
            then it compares the object that is referenced by weak ref with null
            and thereby checks that this object have been GC'ed.

            Covered assertions assert_func106
        </Description>
        <Keyword name="functional"/>    
        <Source name="DeleteLocalRefTest.java"/>
            
        <Runner ID="Runtime">
            <Param name="toRun" value="org.apache.harmony.vts.test.vm.jni.references.DeleteLocalRefTest"/>
        </Runner>
</Test>

=== freeVM/freeVM/enhanced/buildtest/tests/stress/qa/src/test/stress/org/apache/harmony/test/stress/jni/stack/StackTest6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements.  See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership.  The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied.  See the License for the
 specific language governing permissions and limitations
 under the License.
-->
<!DOCTYPE Test SYSTEM "test.dtd">
<!--
Author: Vladimir Nenashev
Version: $Revision: 1.6 $
-->
<Test
	ID="StackTest6"
        date-of-creation="2005-10-19"
        timeout="3">
    	<Copyright value="apache"/>
        <Author value="Vladimir Nenashev"/>
        <Description>
		Java class creates a specified number of threads. Each thread
		fills the memory with some objects and then calls its
		native method. Native method calls itself
		with Call_Type_Method() JNI function specified number of times
		(not so much times to cause stack oveflow).
		Then the method carries out some calculation and returns
		the result to the top level (Java main method).
		Parameters:
			-arrSize - Length of arrays for calculations (1000 by default)
			-invCount - Recursion depth (0 by default)
			-objsize - Object size for memory padding (1000 by default)
			-bufsize - Buffer size to be released after memory padding (500000 by default)
			-threads - Number of threads (100 by default)
			-timeout - Timeout for waiting a thread to die (20 minutes by default)
        </Description>        
        <Keyword name="stress"/>
        <Source name="StackTest6.java"/>

        <Runner ID="Runtime">
            <Option value="-Dorg.apache.harmony.test.share.stress.ReliabilityRunner.params=
					org.apache.harmony.test.stress.jni.stack.StackTest6 {}"/>
		<Option value="-Dorg.apache.harmony.test.stress.jni.stack.share.STStackTest.fillMemory=1"/>
		<Option value="-Dorg.apache.harmony.test.stress.jni.stack.share.STStackTest.invCount=0"/>
			<Param name="toRun" value="org.apache.harmony.test.share.stress.ReliabilityRunner">
			</Param>
		</Runner>
		<Restriction name="OtherVMOnly"/>
</Test>

=== freeVM/freeVM/enhanced/buildtest/tests/functional/src/test/functional/org/apache/harmony/test/func/api/java/util/logging/LoggingPermission/LoggingPermissionTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='../../../../../../../../../../../test.xsl'?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM '../../../../../../../../../../../test.dtd'>
<!-- 
-->


<Test
    ID="LoggingPermissionTest"
    date-of-creation="2005-09-07"
    timeout="1"
    >

    
    
    
    <MulticaseTestDescription>
        <TestedClass name="java.util.logging.LoggingPermission"/>

        <Case ID="testLoggingPermission">
            <TestedMethod name="public LoggingPermission(String name, String actions)"/>
            <Precondition>None</Precondition>
            <Description>creates instances of LoggingPermission with empty and null second
            argument. Checks if an exception is thrown when try to create a LoggingPermission
            instance with first arg that is not "control" one.  
            </Description>
            <Expected>0</Expected>
        </Case>
        
    </MulticaseTestDescription>

    <Keyword name="functional"/>    
    
    <Source name="LoggingPermissionTest.java"/>

    <Runner ID="MultiCase">
        <Param name="toRun" value="org.apache.harmony.test.func.api.java.util.logging.LoggingPermission.LoggingPermissionTest">
                <Option name="-threads" value="$qa.threads"/>
        </Param>
    </Runner>
</Test>
