=== freeVM/freeVM/enhanced/buildtest/tests/vts/vm/src/test/test.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!ELEMENT Test (Copyright+, Author+, (MulticaseTestDescription|APITestDescription|Description), Keyword*, Source+, Modification*, Runner, Resource*, Restriction*)>
<!ATTLIST Test
	ID CDATA #REQUIRED
	date-of-creation CDATA #REQUIRED
	timeout CDATA #REQUIRED>
<!ELEMENT Copyright EMPTY>
<!ATTLIST Copyright
	value CDATA #REQUIRED>
<!ELEMENT Author EMPTY>
<!ATTLIST Author
	value CDATA #REQUIRED>
<!ELEMENT MulticaseTestDescription (TestedClass, Case+)>
<!ELEMENT APITestDescription ((TestedClass, TestedMethod+)+, Description)>
<!ELEMENT TestedClass EMPTY>
<!ATTLIST TestedClass
	name CDATA #REQUIRED>
<!ELEMENT Case (TestedMethod+, (TestedClass, TestedMethod+)*, Precondition?, Description, Expected?)>
<!ATTLIST Case
	ID CDATA #REQUIRED>
<!ELEMENT TestedMethod EMPTY>
<!ATTLIST TestedMethod
	name CDATA #REQUIRED>
<!ELEMENT Precondition (#PCDATA)>
<!ELEMENT Expected (#PCDATA)>
<!ELEMENT Description ANY>
<!ELEMENT Keyword EMPTY>
<!ATTLIST Keyword
	name CDATA #REQUIRED>
<!ELEMENT Source EMPTY>
<!ATTLIST Source
	name CDATA #REQUIRED>
<!ELEMENT Modification EMPTY>
<!ATTLIST Modification
	date CDATA #REQUIRED
	author CDATA #REQUIRED>
<!ELEMENT Runner (Option*, Param+)>
<!ATTLIST Runner
	ID CDATA #REQUIRED>
<!ELEMENT Param (Option*)>
<!ATTLIST Param
	name CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT Option EMPTY>
<!ATTLIST Option
	name CDATA #IMPLIED
	value CDATA #IMPLIED>
<!ELEMENT Resource EMPTY>
<!ATTLIST Resource
	name CDATA #REQUIRED>
<!ELEMENT Restriction EMPTY>
<!ATTLIST Restriction
	name CDATA #REQUIRED>

=== freeVM/freeVM/enhanced/buildtest/tests/functional/src/test/functional/org/apache/harmony/test/func/api/java/lang/ClassLoader/loadClass/loadClass10/loadClass1011/loadClass1011.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='../../../../../../../../../../../../../test.xsl'?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM '../../../../../../../../../../../../../test.dtd'>
<Test
    ID="loadClass1011"
    date-of-creation="2005-6-30"
    timeout="1"
    >
        
        
        <APITestDescription>
            <TestedClass name="java.lang.ClassLoader"/>
            <TestedMethod name="protected Class&lt;?&gt; loadClass(String name, boolean resolve) throws ClassNotFoundException"/>
            <Description>
The test is against the loadClass1011 method.

The test performs the following checks on the method.
1) ClassNotFoundException is thrown if a class with specified name cannot be found.
2) ClassNotFoundException is not thrown if 
   a class with specified name can be found and "boolean resolve" is false.
3) ClassNotFoundException is not thrown if 
   a class with specified name can be found and "boolean resolve" is true.
            </Description>
            </APITestDescription>
        <Source name="loadClass1011.java"/>
        <Runner ID="Runtime">
            <Param name="toRun" value="org.apache.harmony.test.func.api.java.lang.ClassLoader.loadClass.loadClass10.loadClass1011.loadClass1011"/>
        </Runner>
</Test>

=== freeVM/freeVM/enhanced/buildtest/tests/functional/src/test/functional/org/apache/harmony/test/func/reg/vm/btest10305/Btest10305.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='../../../../../../../../../test.xsl'?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM '../../../../../../../../../test.dtd'>
<Test ID="Btest10305" date-of-creation="2006-10-27" timeout="1">
    
    
    
    <Description>
        (JIT_debug: SINGLE_STEP does not work for constructor of java.lang.Object)
    </Description>
    <Keyword name="regression"/>  
    
    <Source name="Btest10305.java"/>
    <Source name="Btest10305.cpp"/>
    
    <Runner ID="Execute">
        <Param name="toRun" value="$TestedRuntime">
            <Option name="-cp" value="$CP"/>
            <Option name="-agentlib:Btest10305"/>
            <Option name="org.apache.harmony.test.func.reg.vm.btest10305.Btest10305"/>
        </Param>        
    </Runner>                               

</Test>

=== freeVM/freeVM/enhanced/buildtest/tests/functional/src/test/functional/org/apache/harmony/test/func/api/javax/management/monitor/countermonitor/GranularityTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='../../../../../../../../../../../test.xsl'?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM '../../../../../../../../../../../test.dtd'>
<!--
-->
<Test
    ID="GranularityTest"
        date-of-creation="2006-03-03"
        timeout="2">
        
        
    <APITestDescription>
        <TestedClass name="javax.management.monitor.CounterMonitor"/>
        <TestedMethod name="public void setGranularityPeriod(long period)"/>
        <TestedMethod name="public void setInitThreshold(Number value)"/>
        <TestedMethod name="public void setModulus(Number value)"/>
        <TestedMethod name="public void setNotify(boolean value)"/>
        <TestedMethod name="public void start()"/>
        <TestedMethod name="public void stop()"/>
        
        <TestedClass name="javax.management.NotificationBroadcasterSupport"/>
        <TestedMethod
            name="public void addNotificationListener(NotificationListener listener,NotificationFilter filter,Object handback)"/>
            
        <TestedClass name="javax.management.monitor.Monitor"/>
        <TestedMethod name="public void addObservedObject(ObjectName object)"/>
        <TestedMethod name="public void setObservedAttribute(String attribute)"/>
        <Description>
            This test verifies setGranularityPeriod method.
            Step by step:
                1. Create the monitor and observed MBean objects. The Monitor and
                Observed MBean has the same granularity period(GP), but the shifted 
                to GP/2 value
                2. After waiting for a reasonable time(~5*GP), change monitors
                granularity period to GP/10 and receive the corresponding notification
        </Description>
    </APITestDescription>        
        <Keyword name="functional"/>
        <Source name="GranularityTest.java"/>        
        <Runner ID="Runtime">
            <Param name="toRun" value="org.apache.harmony.test.func.api.javax.management.monitor.countermonitor.GranularityTest">

            </Param>
        </Runner>
        <Restriction name="OtherVMOnly"/>
</Test>

=== freeVM/freeVM/enhanced/buildtest/tests/functional/src/test/functional/org/apache/harmony/test/func/api/java/nio/charset/CharsetEncoder/CharsetEncoderTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='../../../../../../../../../../../test.xsl'?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM '../../../../../../../../../../../test.dtd'>
<!-- 
-->


<Test
    ID="CharsetEncoderTest"
    date-of-creation="2006-03-10"
    timeout="1"
    >

    
    
    
    <MulticaseTestDescription>
        <TestedClass name="java.nio.charset.CharsetEncoder"/>
        
        <Case ID="testConstructor">
             <TestedMethod name="protected CharsetEncoder(Charset cs, float averageCharsPerByte, float maxCharsPerByte)"/>
             <TestedMethod name="protected CharsetEncoder(Charset cs, float averageCharsPerByte, float maxCharsPerByte, byte[] replacement)"/>
            <Precondition></Precondition>
            <Description>create an instance of a child of CharsetEncoder class with various parameters - nulls, not nulls, negative, etc</Description>
            <Expected>API conformance</Expected>
        </Case>

        <Case ID="testEncode">
             <TestedMethod name="public final CoderResult encode(CharBuffer in, ByteBuffer out, boolean endOfInput)"/>
            <TestedMethod name="public final CoderResult flush(ByteBuffer out)"/>
            <Precondition></Precondition>
            <Description>write data to file using FileChannel and ByteBuffer, encoded from CharBuffer, 
            then flush after everything is finished</Description>
            <Expected>API conformance and that data is really written (check using FileInputStream)</Expected>
        </Case>
        
        <Case ID="testIsLegalReplacement">
             <TestedMethod name="public boolean isLegalReplacement(byte[] repl)"/>
            <Precondition></Precondition>
            <Description>create encoder for UTF-8 and pass various byte arrays to it for check</Description>
            <Expected>API conformance</Expected>
        </Case>
        

    </MulticaseTestDescription>


    <Keyword name="functional"/>    
    
    <Source name="CharsetEncoderTest.java"/>

    <Runner ID="MultiCase">
        <Param name="toRun" value="org.apache.harmony.test.func.api.java.nio.charset.CharsetEncoder.CharsetEncoderTest">
        </Param>
    </Runner>
</Test>

=== freeVM/freeVM/enhanced/buildtest/tests/functional/src/test/functional/org/apache/harmony/test/func/api/java/util/GregorianCalendar/GregorianCalendarTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='../../../../../../../../../../test.xsl'?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM '../../../../../../../../../../test.dtd'>
<!-- 
-->

<Test
    ID="GregorianCalendarTest"
    date-of-creation="2006-14-03"
    timeout="1"
    >

    
    
    
    <MulticaseTestDescription>

        <Case ID="testComputeFields">
            <TestedClass name="java.util.GregorianCalendar"/>
            <TestedMethod name="protected void computeFields()"/>
            <TestedClass name="java.util.Calendar"/>
            <TestedMethod name="public final void clear()"/>
            <TestedMethod name="public final boolean isSet(int field)"/>
            <Precondition></Precondition>
            <Description></Description>
            <Expected></Expected>
        </Case>
        
        <Case ID="testComputeTime">
            <TestedClass name="java.util.GregorianCalendar"/>
            <TestedMethod name="protected void computeTime()"/>            
            <TestedClass name="java.util.Calendar"/>
            <TestedMethod name="protected void complete()"/>
            <TestedMethod name="public final void clear()"/>
            <TestedMethod name="public final boolean isSet(int field)"/>
            <Precondition></Precondition>
            <Description></Description>
            <Expected></Expected>
        </Case>

         <TestedClass name="java.util.Calendar"/>
        
        <Case ID="testCalendarConstructor">
            <TestedMethod name="protected Calendar(TimeZone zone, Locale aLocale)"/>
            <TestedMethod name="public TimeZone getTimeZone()"/>
            <Precondition></Precondition>
            <Description></Description>
            <Expected></Expected>
        </Case>
        
        <Case ID="testIsSet">
            <TestedMethod name="protected Calendar()"/>
            <TestedMethod name="public final void clear()"/>
            <TestedMethod name="public void set(int field, int value)"/>
            <TestedMethod name="public final boolean isSet(int field)"/>            
            <Precondition></Precondition>
            <Description></Description>
            <Expected></Expected>
        </Case>

    </MulticaseTestDescription>
    <Keyword name="functional"/>
    <Source name="GregorianCalendarTest.java"/>

    <Runner ID="MultiCase">
        <Param name="toRun" value="org.apache.harmony.test.func.api.java.util.GregorianCalendar.GregorianCalendarTest">
        </Param>
    </Runner>
</Test>

=== freeVM/freeVM/enhanced/buildtest/tests/vts/vm/src/test/vm/jvms/instructions/invokeReturn/invokevirtual/invokevirtual13/invokevirtual1309/invokevirtual1309.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM "test.dtd">
<!--
Author: Ilia A. Leviev
Version: $Revision: 1.3 $
-->
<Test
  ID="invokevirtual1309"
  date-of-creation="2005-09-08"
  timeout="1"
  >
  <Author value="Ilia A. Leviev"/>
  <Description>
    Tests invokevirtual java virtual machine instruction.    
    The LinkageError is thrown if protected method is member of class S that superclass of direct superclass of current class and type of object is direct superclass.
   Covered assertions assert_instr26a369 assert_instr26a371
</Description>

  <Source name="invokevirtual1309w.j"/>
  <Source name="invokevirtual1309n.j"/>
  <Source name="invokevirtual1309super2.j"/>
  <Source name="invokevirtual1309super.j"/>
  <Runner ID="Runtime">
    <Param name="toRun" value="org.apache.harmony.vts.test.vm.jvms.instructions.invokeReturn.invokevirtual.invokevirtual13.invokevirtual1309.invokevirtual1309w"/>
  </Runner>
</Test>

=== freeVM/freeVM/enhanced/buildtest/tests/functional/src/test/functional/org/apache/harmony/test/func/api/java/lang/Object/hashCode/hashCode10/hashCode1010/hashCode1010.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='../../../../../../../../../../../../../test.xsl'?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM '../../../../../../../../../../../../../test.dtd'>
<Test
    ID="hashCode1010"
    date-of-creation="2005-6-30"
    timeout="1"
    >
        
        
        <APITestDescription>
            <TestedClass name="java.lang.Object"/>
            <TestedMethod name="public int hashCode()"/>
            <Description>
The test is against hashCode1010 method.

The test performs the following checks on values returned by the method.
1) Whenever it is invoked on the same object more than once 
   during an execution of a Java application, 
   the hashCode method must consistently return the same integer, 
   provided no information used in equals comparisons on the object is modified. 
2) If two objects are equal according to the equals(Object) method,
   then calling the hashCode method on each of the two objects
   must produce the same integer result.  
            </Description>
            </APITestDescription>
        <Source name="hashCode1010.java"/>
        <Runner ID="Runtime">
            <Param name="toRun" value="org.apache.harmony.test.func.api.java.lang.Object.hashCode.hashCode10.hashCode1010.hashCode1010"/>
        </Runner>
</Test>

=== freeVM/freeVM/tests/functional/src/test/functional/org/apache/harmony/test/func/api/java/security/F_AccessControlContextTest_01/F_AccessControlContextTest_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='../../../../../../../../../../test.xsl'?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM '../../../../../../../../../../test.dtd'>
<Test
    ID="F_AccessControlContextTest_01"
    date-of-creation="2004-12-06"
    timeout="1"
    >
    <!--
    -->
            
                
                <APITestDescription>
                    <TestedClass name="java.security.AccessController"/>
                    <TestedMethod name="public static AccessControlContext getContext()"/>
                    <TestedMethod name="public static &lt;T&gt; T doPrivileged(PrivilegedAction&lt;T&gt; action)"/>

                    <TestedClass name="java.security.AccessControlContext"/>
                    <TestedMethod name="public AccessControlContext(ProtectionDomain[] context)"/>
                    <TestedMethod name="public AccessControlContext(AccessControlContext acc, DomainCombiner combiner)"/>

                    <TestedClass name="java.security.Policy"/>
                    <TestedMethod name="public static Policy getPolicy()"/>
                    <TestedMethod name="public PermissionCollection getPermissions(ProtectionDomain domain)"/>

                    <TestedClass name="java.security.ProtectionDomain"/>
                    <TestedMethod name="public ProtectionDomain(CodeSource codesource, PermissionCollection permissions, ClassLoader classloader, Principal[] principals)"/>                    
                    <TestedMethod name="public final CodeSource getCodeSource()"/>

                    <TestedClass name="java.security.PermissionCollection"/>
                    <TestedMethod name="public PermissionCollection()"/>

                    <TestedClass name="java.security.Security"/>
                    <TestedMethod name="public static String getProperty(String key)"/>

                    <TestedClass name="java.security.Permissions"/>
                    <TestedMethod name="public Enumeration&lt;Permission&gt; elements()"/>

                    <Description>
                        Check AccessControlContext security mechanism.
                    </Description>
                </APITestDescription>
                
                <Keyword name="functional"/>
                <Source name="F_AccessControlContextTest_01.java"/>
                <Modification date="2004-12-06" />                

        <Runner ID="Runtime">
                <Option name="-cp" value="$CP$PathSeparator$TestSuiteClassRoot$PathSeparator"/>
                   <Option name="-Djava.security.policy==$TestDirectory$FileSeparatorauxiliary$FileSeparatorAccessControlContext01.policy"/>
                   <Option name="-Dqe.suite=$TestSuiteRoot"/>
                   <Option name="-Dqe.class=$TestSuiteClassRoot"/>
                   <Option name="-Dqe.src=$TestSuiteTestRoot"/>
            <Param name="toRun" value="org.apache.harmony.test.func.api.java.security.F_AccessControlContextTest_01.F_AccessControlContextTest_01"/>
                
        </Runner>
        <Restriction name="OtherVMOnly"/>

</Test>
